src/Translatable/Translatable.php

This fixes the error you might get if the developer uses a custom locale key.

Fixing the static `locale` key in the listsTranslations scope

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

PR for #116
Make $country->{'name:en'} or $country['name:en'] synonym for $country->translate('en')->name
Easier to automate form building/submissions.

Add mutator/accessor translations

---

src/Translatable/Translatable.php

I think this is necessary because laravel just noted that getLocale
isn't in the app contract at
https://github.com/laravel/lumen-framework/pull/95#issuecomment-101180266

getLocale function removed

---

readme.md

reminding about protected $width on eloquent model that might be handy if user needs translations all the time

Update readme.md add $width commented as part of documentation

---

src/Translatable/Translatable.php

Set `$locale` default null and get current system locale
```php
$elems = Model::translatedIn()->get()
```
return records with current locale translation .

Add retriving default locale for translatedIn method

---

readme.md
src/Translatable/Translatable.php
src/config/translatable.php
tests/TranslatableTest.php
tests/migrations/2013_11_28_152610_create_tables.php
tests/models/Food.php
tests/models/FoodTranslation.php

It is now possible to use country based locales. For example, you can have the following locales:
- English: `en`
- Spanish: `es`
- Mexican Spanish: `es-MX`
- Colombian Spanish: `es-CO`
To configuration for these locales looks like this:
```php
'locales' => [ 
'en',
'es' => [
'MX',
'CO',
],
];
```
We can also configure the "glue" between the language and country. If for instance we prefer the format `es_MX` instead of `es-MX`, 
the configuration should look like this:
```php
'locale_separator' => '_',
```
What applies for the fallback of the locales using the `en-MX` format? 
Let's say our fallback locale is `en`. Now, when we try to fetch from the database the translation for the 
locale `es-MX` but it doesn't exist,  we won't get as fallback the translation for `en`. Translatable will …

Country locales

---

readme.md
src/Translatable/Translatable.php
tests/ScopesTest.php

Hi Dismav, 
I'm currently using your package in some of my projects.
In order to implement easily some search functions I currently use this scope: WhereTranslationLike
I hope it can be useful to someone else :)
Bye,
Karoly

scopeWhereTranslationLike

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

The bug occurs when you call toArray() on a model where a translation
does not exist for the current app locale and you have a translation
for the fallback locale set in the translatable.config
In this case you expect toArray() to merge the $translatedProperties
with the fallback translation, but this does not happen.
Added test to confirm bug is solved.
``` php
return [
'locales' => [
'nb' => [
,
],
'da' => [
'DK',
]
],
'locale_separator' => '_',
'locale' => null,
'use_fallback' => true,
'fallback_locale' => 'nb',
'translation_suffix' => 'Translation',
'locale_key' => 'locale',
'always_fillable' => false,
];
```
``` php
// lets say we have a food model with a $translatedAttributes =
['name'];
Food::create([
'id' => 1,
'nb' => [
'name' => 'test'
]
]);
app()->setLocale('da_DK');
$food = …
```

BUGFIX: Fixed a bug in locale fallback on toArray()

---

src/Translatable/Translatable.php
tests/ScopesTest.php

Added a scope (`notTranslatedIn`) for fetching by those who doesn't have a specific translation.
Useful for creating a view to translate content and filtering by missing translations.

Added notTranslatedIn scopes

---

src/Translatable/Translatable.php

When using Lumen without Facades this package becomes incompatible. Use app() helper instead for full compatibility.

Add support for Lumen w/o Facades

---

src/Translatable/Translatable.php
tests/TranslatableTest.php
tests/migrations/2013_11_28_152610_create_tables.php
tests/models/Person.php
tests/models/PersonTranslation.php

Add support for Model accessors to be called

---

CHANGELOG.md
readme.md
src/Translatable/Translatable.php
src/config/translatable.php
tests/TestCoreModelExtension.php
tests/TranslatableTest.php
tests/models/City.php
tests/models/CityTranslation.php
tests/models/Country.php
tests/models/CountryStrict.php
tests/models/CountryTranslationGuarded.php
tests/models/Food.php
tests/models/FoodTranslation.php
tests/models/Person.php
tests/models/PersonTranslation.php
tests/models/StrictTranslation.php

Translated fillable properties should only be defined in the translation model.

Translated fillable definition

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

Fix issue when trying to fetch a translation with a country based (e.g. 'pt-PT') and the only translation available is for the fallback locale.
Cover the scenario where the configured fallback locale is 'en', you are trying to fetch a translation for 'pt-PT' but the model only has a translation to 'en'. As it was before the code would attempt to fetch a translation for 'pt' twice instead of trying 'pt' first and then use the configured fallback locale.

Fix issue when trying to fetch a translation with a country based locale

---

changelog.md
readme.md
src/Translatable/Translatable.php
src/config/translatable.php
tests/TranslatableTest.php

- Skip translations in toArray() when configured unless translations already loaded.

toArray() performance

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

This will allow to return the translation in the desired locale, by calling the attribute on the model without the need of changing the application locale using App::setLocale();

A model can have a default locale for translations

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

Hello, guys! While I was writing tests for #347, I noticed that `fill()` method produces different results depending on how we pass data to it. Here what I mean (example from readme.md):
```php
// First, using the locale as array key.
$greece = $country->fill([
'en'  => ['name' => 'Greece'],
'fr'  => ['name' => 'Grèce'],
]);
// The second way is to use the following syntax.  
$greece = $country->fill([
'name:en' => 'Greece',
'name:fr' => 'Grèce',
]);
```
The difference appears when one (or many) of passed languages is not exists in `translatable.locales` config array. Unknown languages must be ignored, and they are ignored in example 1, but not in second example. There are some tests to illustrate this issue.

Fixed: different results using fill() method with same data

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

According to issue #273, it would be great to have a way to retrieve translations in the same structure such as for saving (like `fill()` method). For example I have a view with a form for updating some of my translatable records. My form fields named `en[title]`, `en[description]`, `es[title]` and so on. It is easy to store these data (via `create()` or `fill()` methods), and they can be easily passed to the view via `$input->old()` method. But there is no way to retrive and pass translations data to the view directly from translatable model, because their stucture is different. What do you think about it?

added getTranslationsArray() method

---

src/Translatable/Translatable.php

I use Translatable along with a model logging package that uses events to log changes. Deleting translations did not log (deleted event didn't fire) because they were deleted directly from the QueryBuilder, not model instances.

Delete via model instead of QueryBuilder

---

src/Translatable/Translatable.php
tests/TestsBase.php
tests/TranslatableTest.php

This is a fix for following [issue](https://github.com/dimsav/laravel-translatable/issues/283). The solution is derived from one of the user's work around.

Translate on different connection

---

composer.json

I've run the unit tests locally and everything looks good. This fork is working on a Laravel 5.5 project without any noticeable problems.

Upgraded dependencies to support Laravel 5.5

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

* avoid fetching attribute on non-object on empty translation when fallback translation is not available
* added phpunit testing with empty translation and without a fallback translation
Completes https://github.com/dimsav/laravel-translatable/pull/396

Avoid fetching attribute on non-object on empty translation when fallback translation is not available

---

src/Translatable/Translatable.php
tests/ScopesTest.php
tests/TestsBase.php
tests/models/Vegetable.php
tests/seeds/AddFreshSeeds.php

This PR fixes two separate but related issues with the `withTranslation` query scope.
As reported in #241, the generated SQL has an error that will cause it to incorrectly fetch all of the translations for the default language:
```
SELECT * FROM `xxx_translations
WHERE `xxx_translations`.`product_id` IN ('59') AND
`xxx_translations`.`locale` = 'fr' OR `xxx_translations`.`locale` = 'en'`
^ parenthesis is missing here                                ... and here ^
```
This can be fixed by wrapping the `OR` clauses in parentheses (by using the adequate query builder methods), or simply by using a `WHERE IN` statement. I chose the latter option.
---
When using country-based fallbacks, the language fallback wasn't appended to the SQL request. So, to build on the current [example …

Fix withTranslation query scope performance issues and fallback for country-based locales

---

src/Translatable/Translatable.php

When the `model_translations` table is empty or the related key from the `models` table is not assigned yet, i.e not translated, the original attribute value is returned as `null` so there is no text! This is a proposed solution for that issue.

Solving the issue of empty attribute values

---

composer.json

This avoids having things like:
```
'TestCoreModelExtension' => $vendorDir . '/dimsav/laravel-translatable/tests/TestCoreModelExtension.php',
'TestsBase' => $vendorDir . '/dimsav/laravel-translatable/tests/TestsBase.php',
'TranslatableTest' => $vendorDir . '/dimsav/laravel-translatable/tests/TranslatableTest.php',
```
Show up on your production autoload_classmap file when installed with `--no-dev`

Move tests autoload classmap to dev

---

.styleci.yml

https://styleci.readme.io/docs/change-log#section-14042018-april-fixer-updates
> Finally, the long deprecated "linting" config option has now been removed.

remove deprecated linting

---

.styleci.yml

https://styleci.readme.io/docs/change-log#section-14042018-april-fixer-updates
> Finally, the long deprecated "linting" config option has now been removed.

remove deprecated styleci linting

---

src/Translatable/Translatable.php

During review of #108 I recognized that the doc-tag of getTranslationOrNew() is wrong. It returns a model instance in every case.

Fix return type

---

src/Translatable/Translatable.php

solves #456
The normal laravel `save` method fires `saving` in every case - independent of dirty or anything else. This shouldn't be changed.

fire saving event in every case

---

readme.md

The `whereTranslation` scope allows for a third parameter `$locale` that filters translations in that locale.
I needed that feature to filter slugs in specific locales.
Example:
`example.com/map` -> map page in english
`example.com/sv/karta` -> map page in swedish
The problem is that I was querying the pages model using the slug and `sv/map` would return (correctly) the map page instance, but that's not a correct locale/slug combination.
To make that work using the provided scope it should filter also by locale, which that third parameter enables.
I wasn't aware of it until I went into the source code to try and fix my problem, and the "fix" was already there.
Docs updated so that anybody with the same issue is aware of the option.

example in doc for locale filtering in whereTranslation scope

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

Currently the `translateOrDefault` method requires a local parameter.
This PR adds a default value of  `null` to the locale parameter.
This way the locale defaults to the current `app.locale`. It also adds consistency with the `translate` method.

Allow translateOrDefault to user app locale

---

readme.md
src/Translatable/Translatable.php
tests/ScopesTest.php
tests/TestsBase.php

This introduces three new static methods to control the autoload translations behavior.
* `enableAutoloadTranslations()` - forces to load all translations
* `disableAutoloadTranslations()` - disables autoload and returns parent attributes
* `defaultAutoloadTranslations()` - does not change the old behavior logic (*default*)
**solves:**
* #482 
* #483

Change autoload translations behavior on runtime

---

src/Translatable/Translatable.php
tests/ScopesTest.php

I made a new scope to order results by translation fields.
```
Countries::orderByTranslation('name')->get();
```
will order the results based on the `name` attribute inside the translation table. 
```
Countries::orderByTranslation('name', 'desc')->get();
```
will do the same but in descending order

added orderByTranslation scope

---

src/Translatable/Translatable.php
tests/TranslatableTest.php

**replaces:** #466 by @Gummibeer 
**solves:**
* #448

use fallback in attributesToArray

---

composer.json
readme.md
tests/ScopesTest.php
tests/TestCoreModelExtension.php
tests/TestsBase.php
tests/TranslatableTest.php

- Removes the direct dependency on phpunit
(since is required by orchestra/testbench)
- Update tests to support phpunit 8.0.0 (some methods were deprecated)

Update to Laravel 5.8

---

readme.md
src/Translatable/Translatable.php
tests/TestCoreModelExtension.php
tests/TranslatableTest.php
tests/migrations/2013_11_28_152610_create_tables.php

fixes #393 
fixes #543 
fixes #573

add isEmptyTranslatableAttribute() to allow custom decision logic

---

src/Translatable/Translatable.php

normalize foreign key

---

src/Translatable/Locales.php
src/Translatable/Translatable.php
src/Translatable/TranslatableServiceProvider.php
tests/LocalesTest.php
tests/TestsBase.php
tests/TranslatableTest.php

replaces #323 with credits
thanks again @deargonaut for the idea and help!

 add locales helper class

---

src/Translatable/Translatable.php

https://github.com/FriendsOfPHP/PHP-CS-Fixer
```php
<?php
$finder = \PhpCsFixer\Finder::create()
->in('src/Translatable');
$config = \PhpCsFixer\Config::create()
->setRules([
'ordered_class_elements' => [
'sortAlgorithm' => 'alpha',
'order' => [
'use_trait',
'constant_public',
'constant_protected',
'constant_private',
'property_public',
'property_protected',
'property_private',
'construct',
'destruct',
'magic',
'phpunit',
'method_public',
'method_protected',
'method_private',
],
],
])
->setFinder($finder);
return $config;
```

order translatable class elements
