- src/Translatable/Translatable.php
- tests/TestCoreModelExtension.php
This pull request suggested to solve this issue #133
> Make attributes hidden

- src/Translatable/Translatable.php
Added docblocks to the `Translatable` trait for IDE autocompletion.
> Docblocks in Translatable

- readme.md
> Fix broken link in README

- readme.md
For Laravel 5.x users  (PHP 5.5.x ), it will be easier to grab it without change :)
> Teeny tiny change in readme

- src/Translatable/Translatable.php
A small but helpful refactor (at least for my case)
There is no harm in small bits of refactoring right:)
Thanks, Hyl
> Used isTranslationAttribute method in setAttribute

- CHANGELOG.md
- Fixed a broken link to an issue
- Added a missing link
- Minor tweaks for more consistency
> Fix minor issues on CHANGELOG

- src/Translatable/Translatable.php
Fire updated event as discussed in #175
> Fire updated event when saving translations

- src/Translatable/Translatable.php
> Typehinted variables.

- readme.md
- src/Translatable/Translatable.php
added the following methods
forgetTranslations()
forgetTranslation(array)
syncTranslations(array)
and updated the readme
> Forget translation

- changelog.md
- readme.md
- src/Translatable/Translatable.php
- tests/TranslatableTest.php
> Fill with locale

- src/Translatable/Translatable.php
- tests/ScopesTest.php
We noticed some scopes were missing, so we added them.
Hope this helps!
> Added orWhereTranslation and orWhereTranslationLike scopes

- changelog.md
- composer.json
- Support for laravel auto-discovery
> Auto-discovery

- changelog.md
- readme.md
- src/Translatable/TranslatableServiceProvider.php
> Added tag for vendor publishing.

- readme.md
fix sorting by translated data so that where clause is inside the join
> fix sorting by translated data

- src/Translatable/Translatable.php
i think using config helper function will remove temp vars , and reduce the code a little bit .
> Use config helper function

- src/config/translatable.php
> add additional hint for locale config

- src/Translatable/Translatable.php
The config says `Note that 'use_fallback' must be enabled.` so this should be done in the code.
> combine use_fallback and use_property_fallback

- composer.json
> remove minimum-stability

- composer.json
> increase php minimum version

- src/Translatable/Translatable.php
> do not call get translation with fallback locale and fallback enabled

- src/Translatable/Translatable.php
- tests/TranslatableTest.php
> use fallback in attributesToArray

- readme.md
- src/Translatable/Translatable.php
- tests/ScopesTest.php
- tests/TestsBase.php
**replaces:** #484 by @Gummibeer 
**solves:**
* #482
* #483
> Change autoload translations behavior on runtime

- .circleci/config.yml
**solves:** #510 
solution copied from https://github.com/sinkcup/wifidog-auth-laravel/issues/1
> run composer self-update as sudo

- tests/TranslatableTest.php
- tests/models/CountryWithCustomLocaleKey.php
- tests/models/CountryWithCustomTranslationModel.php
> add unittest for customized translation model

- changelog.md
Updated changelog to include notes from latest release
> updated changelog

- .circleci/config.yml
- composer.json
- phpunit.xml
- tests/TestsBase.php
- tests/TranslatableTest.php
> upgrade everything for Laravel 5.8

- src/Translatable/Translatable.php
> drop custom save method in favor of saved event listener

- .circleci/config.yml
- src/Translatable/Translatable.php
This PR shouldn't be BC but I have marked some spots that need updates which are BC
**blocked by:** #558
> use php7.1 type hints and drop all comments/doc-blocks
